# Site settings
author: Alison Williams
title: Albee's Coding Buzz
header-img: img/home-bg.png
email: apw5011@gmail.com
copyright_name: Alison Williams
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AlisonW417

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
